# Generated by Django 5.0.4 on 2024-05-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.SmallIntegerField(choices=[(0, 'bugalter'), (1, 'omborchi')], default=0),
        ),
    ]
