# Generated by Django 5.0.4 on 2024-05-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Parol',
            },
        ),
    ]
