# Generated by Django 5.0.4 on 2024-05-05 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.category'),
        ),
        migrations.AddField(
            model_name='productinput',
            name='input_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productoutput',
            name='output_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
