# Generated by Django 5.0.4 on 2024-05-05 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinput',
            old_name='responsible_user_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='productoutput',
            old_name='responsible_user_id',
            new_name='user_id',
        ),
    ]
