# Generated by Django 5.0.4 on 2024-05-10 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productinput_all_quantity_productoutput_all_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinput',
            name='all_quantity',
        ),
    ]
