# Generated by Django 5.0.4 on 2024-05-12 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoutput',
            name='all_quantity',
        ),
    ]
