# Generated by Django 5.0.4 on 2024-06-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_category_name_alter_unit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinput',
            name='all_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='productoutput',
            name='all_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
